import{calendarQueryRange,cleanTemporalText,temporalData}from"./temporal.js?v=0.18.2";

export const VALID_INTENTS=["note","task.create","reminder.create","calendar.create","calendar.query","calendar.update","calendar.delete","contact.call","file.store","photo.store"];
const SENSITIVE_INTENTS=new Set(["calendar.update","calendar.delete","contact.call"]);
const MAX_TEXT_LENGTH=500,MIN_CONFIDENCE=0.75;
const INTERPRETER_URL="https://angeli-ai-interpreter-172772694205.europe-southwest1.run.app/interpret";
const EMPTY={title:null,date:null,time:null,rangeStart:null,rangeEnd:null,location:null,contactName:null,phone:null,notes:null,target:null,changes:null};

export async function interpret(text,{provider=mockProvider,fallback}={}){try{const intent=validateIntent(await provider(text));if(intent.confidence<MIN_CONFIDENCE)throw new Error("Baja confianza");return{...intent,source:"ai"}}catch(e){const local=typeof fallback==="function"?fallback(text):fallback;return{...validateIntent(local),source:"local"}}}

export async function remoteProvider(text,idToken){if(!idToken)throw new Error("IA sin conexión");const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(INTERPRETER_URL,{method:"POST",headers:{Authorization:`Bearer ${idToken}`,"Content-Type":"application/json"},body:JSON.stringify({text,now:new Date().toISOString(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Europe/Madrid"}),signal:controller.signal});if(!response.ok)throw new Error(`IA no disponible (${response.status})`);return await response.json()}finally{clearTimeout(timeout)}}

export async function mockProvider(text){const value=(text||"").trim(),lower=value.toLowerCase(),temporal=temporalData(value),base={...EMPTY,confidence:.9,requiresConfirmation:false};if(/\b(?:cancela|cancelar|borra|borrar|anula|anular)\b/.test(lower))return{...base,intent:"calendar.delete",confidence:.94,target:{title:targetTitle(value,/^(?:cancela(?:r)?|borra(?:r)?|anula(?:r)?)\s+(?:la\s+|el\s+)?/i),date:temporal.scheduledDate||null,time:temporal.scheduledTime||null},requiresConfirmation:true};if(/\b(?:pasa|cambia|mueve|modifica)\b/.test(lower)&&/\b(?:reunión|cita|evento|visita|cena)\b/.test(lower))return{...base,intent:"calendar.update",confidence:.91,target:{title:targetTitle(value,/^(?:pasa|cambia|mueve|modifica)\s+(?:la\s+|el\s+)?/i),date:null,time:null},changes:{date:temporal.scheduledDate||null,time:temporal.scheduledTime||null},requiresConfirmation:true};if(/\b(?:qué|que)\s+(?:tengo|hay)|\b(?:muéstrame|muestrame|consulta)\s+(?:mi\s+)?(?:agenda|calendario)\b/.test(lower))return{...base,intent:"calendar.query",confidence:.91,...(calendarQueryRange(value)||{}),requiresConfirmation:false};if(/\b(?:recuérdame|recordar)\b/.test(lower))return{...base,intent:"reminder.create",confidence:.92,title:value,date:temporal.scheduledDate||null,time:temporal.scheduledTime||null,contactName:contactName(value),requiresConfirmation:Boolean(temporal.scheduledDate&&temporal.scheduledTime)};if(/\b(?:hacer|comprar|preparar|enviar|revisar)\b/.test(lower))return{...base,intent:"task.create",confidence:.9,title:value,date:temporal.scheduledDate||null,time:temporal.scheduledTime||null,requiresConfirmation:false};if(/\b(?:llama|llamar|telefonea|telefonear|contacta|contactar)\b/.test(lower)){const contactNameValue=contactName(value);if(temporal.scheduledDate&&temporal.scheduledTime)return{...base,intent:"reminder.create",confidence:.94,title:`Llamar a ${contactNameValue||"contacto"}`,date:temporal.scheduledDate,time:temporal.scheduledTime,contactName:contactNameValue,phone:null,requiresConfirmation:true};return{...base,intent:"contact.call",confidence:.92,contactName:contactNameValue,phone:null,requiresConfirmation:true}}if(temporal.scheduledDate&&temporal.scheduledTime)return{...base,intent:"calendar.create",confidence:.93,title:calendarTitle(value),date:temporal.scheduledDate,time:temporal.scheduledTime,location:location(value),requiresConfirmation:true};return{...base,intent:"note",confidence:.8,title:value,requiresConfirmation:false}}

export function validateIntent(raw){if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("Respuesta IA no válida");const allowed=new Set(["intent","confidence","title","date","time","rangeStart","rangeEnd","location","contactName","phone","notes","target","changes","requiresConfirmation"]);if(Object.keys(raw).some(key=>!allowed.has(key)))throw new Error("Campo IA no permitido");if(!VALID_INTENTS.includes(raw.intent))throw new Error("Intent IA no permitido");if(typeof raw.confidence!=="number"||raw.confidence<0||raw.confidence>1)throw new Error("Confianza IA no válida");const normalized={...EMPTY,intent:raw.intent,confidence:raw.confidence,requiresConfirmation:Boolean(raw.requiresConfirmation)};for(const key of["title","location","contactName","phone","notes"]){if(raw[key]!==undefined&&raw[key]!==null){if(typeof raw[key]!=="string"||raw[key].length>MAX_TEXT_LENGTH)throw new Error("Texto IA no válido");normalized[key]=raw[key].trim()||null}}for(const key of["date","time","rangeStart","rangeEnd"]){if(raw[key]!==undefined&&raw[key]!==null){if(!isValidTemporal(key,raw[key]))throw new Error("Fecha u hora IA no válida");normalized[key]=raw[key]}}if(normalized.rangeStart&&normalized.rangeEnd&&normalized.rangeStart>=normalized.rangeEnd)throw new Error("Intervalo IA no válido");normalized.target=normalizeTarget(raw.target);normalized.changes=normalizeChanges(raw.changes);if(SENSITIVE_INTENTS.has(normalized.intent))normalized.requiresConfirmation=true;return normalized}

function normalizeTarget(target){if(target===undefined||target===null)return null;if(typeof target!=="object"||Array.isArray(target))throw new Error("Objetivo IA no válido");const allowed=new Set(["title","date","time"]);if(Object.keys(target).some(key=>!allowed.has(key)))throw new Error("Objetivo IA no permitido");if(typeof target.title!=="string"||!target.title.trim()||target.title.length>MAX_TEXT_LENGTH)throw new Error("Título objetivo no válido");if(target.date!==null&&target.date!==undefined&&!isValidTemporal("date",target.date))throw new Error("Fecha objetivo no válida");if(target.time!==null&&target.time!==undefined&&!isValidTemporal("time",target.time))throw new Error("Hora objetivo no válida");return{title:target.title.trim(),date:target.date||null,time:target.time||null}}
function normalizeChanges(changes){if(changes===undefined||changes===null)return null;if(typeof changes!=="object"||Array.isArray(changes))throw new Error("Cambios IA no válidos");const allowed=new Set(["title","date","time","location","notes"]);if(Object.keys(changes).some(key=>!allowed.has(key)))throw new Error("Cambio IA no permitido");const result={};for(const key of allowed){if(changes[key]===undefined||changes[key]===null)continue;if(["date","time"].includes(key)){if(!isValidTemporal(key,changes[key]))throw new Error("Cambio temporal no válido");result[key]=changes[key]}else{if(typeof changes[key]!=="string"||changes[key].length>MAX_TEXT_LENGTH)throw new Error("Cambio de texto no válido");result[key]=changes[key].trim()}}return Object.keys(result).length?result:null}
function isValidTemporal(type,value){if(typeof value!=="string")return false;if(type==="time")return/^([01]\d|2[0-3]):[0-5]\d$/.test(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T12:00:00`);return!Number.isNaN(date.getTime())&&date.toISOString().slice(0,10)===value}
function targetTitle(text,prefix){return cleanTemporalText((text||"").replace(prefix,"").replace(/\b(?:de|del)\s+(?:mañana|domingo|lunes|martes|miércoles|jueves|viernes|sábado)\b/gi,"").trim())}
function calendarTitle(text){return cleanTemporalText(text).replace(/^\s*(?:me\s+han\s+)?contratad[oa]\s+(?:una?\s+)?/i,"").replace(/\s+en\s+[\p{L}][\p{L}\s-]{1,60}$/iu,"").trim()||"Evento de Angeli Secretaria"}
function contactName(text){const match=(text||"").match(/\b(?:llama(?:r)?|telefonea(?:r)?|contacta(?:r)?)\s+(?:a\s+|al\s+)?(.+?)(?:[.!?,;]|$)/i);if(!match)return null;const value=cleanTemporalText(match[1]).replace(/\b(?:mañana|hoy|luego|por favor)\b.*$/i,"").trim();return value||null}
function location(text){const match=(text||"").match(/\ben\s+([\p{L}][\p{L}\d\s,.'’-]{1,100})(?:[.!?;]|$)/iu);return match?match[1].trim().replace(/,$/,""):null}
