import{MEDIA_STORES,readNotes,writeNotes,clearNotes,migrateLegacyImages,putMedia,getMedia,deleteMedia,deleteMediaDB}from"./storage.js?v=0.14";
import{classify,actionData}from"./classifier.js?v=0.14";
import{sendEntry}from"./sheets.js?v=0.14";
import{createUI}from"./ui.js?v=0.14";
import{createGoogleIntegration}from"./google.js?v=0.14";

const ui=createUI({getMedia:(store,id)=>getMedia(store,id)});const $=ui.$;
let notes=[],rec=null,listening=false,finalText="",pendingImages=[],pendingFiles=[],selectedFilter="all",selectedType="all";
function render(){ui.render({notes,selectedFilter,selectedType,google})}
function save(nextNotes=notes){try{writeNotes(nextNotes);notes=nextNotes;render();return true}catch(e){ui.notify(e.name==="QuotaExceededError"?"No hay espacio para guardar la foto. Reduce o elimina entradas con imágenes.":"No se pudo guardar la entrada");return false}}
const google=createGoogleIntegration({notify:ui.notify,refresh:render,setStatus:ui.setGoogleStatus,saveNotes:save,getNotes:()=>notes});
async function load(){notes=readNotes();if(await migrateLegacyImages(notes))save(notes);let changed=false;notes=notes.map(note=>{const type=note.type||classify(note.text,note.images||[],note.files||[]),data=actionData(note.text,type);if(type==="calendar"&&!note.calendarStatus)note.calendarStatus="pending";const needsData=Object.entries(data).some(([key,value])=>note[key]!==value);if(note.type&&!needsData)return note;changed=true;return{...note,type,...data}});if(changed)save(notes);google.updateStatus();render()}
async function add(){const text=$("text").value.trim();if(!text&&!pendingImages.length&&!pendingFiles.length){ui.notify("No hay nada que guardar");return}const now=new Date(),id=crypto.randomUUID(),images=[],files=[];try{for(const file of pendingImages){const mediaId=crypto.randomUUID();await putMedia(MEDIA_STORES.images,{id:mediaId,blob:file,type:file.type,size:file.size});images.push(mediaId)}for(const file of pendingFiles){const mediaId=crypto.randomUUID();await putMedia(MEDIA_STORES.files,{id:mediaId,blob:file,name:file.name,type:file.type,size:file.size});files.push({id:mediaId,name:file.name,type:file.type,size:file.size})}}catch(e){ui.notify("No se pudieron guardar los archivos o imágenes");return}const type=classify(text,images,files),entry={id,date:now.toISOString(),text,status:"pending",type,...actionData(text,type),...(type==="calendar"?{calendarStatus:"pending"}:{}),images,files};if(!save([entry,...notes])){try{await Promise.all([...images.map(mediaId=>deleteMedia(MEDIA_STORES.images,mediaId)),...files.map(file=>deleteMedia(MEDIA_STORES.files,file.id))])}catch(e){}return}$("text").value="";finalText="";pendingImages=[];pendingFiles=[];$("preview").innerHTML="";ui.notify("Guardando en Google…");try{await sendEntry(entry,now);ui.notify("Entrada enviada a Google")}catch(e){ui.notify("Guardada localmente · Google no respondió")}}
function stop(){listening=false;if(rec){try{rec.stop()}catch(e){}}rec=null;$("mic").classList.remove("listening");$("mic").textContent="🎙️ Dictar";$("hint").textContent="Dictado terminado. Pulsa «Guardar» cuando termines."}
function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){ui.notify("Este navegador no admite dictado");return}if(listening){stop();return}finalText=$("text").value.trim();rec=new SR();rec.lang="es-ES";rec.continuous=false;rec.interimResults=true;rec.maxAlternatives=1;let sessionFinal=finalText||"",lastInterim="";rec.onstart=()=>{listening=true;$("mic").classList.add("listening");$("mic").textContent="⏹️ Parar";$("hint").textContent="Escuchando…"};rec.onresult=e=>{let finalPart="",interimPart="";for(let i=e.resultIndex;i<e.results.length;i++){const result=e.results[i],phrase=(result[0]?.transcript||"").trim();if(!phrase)continue;if(result.isFinal)finalPart+=(finalPart?" ":"")+phrase;else interimPart+=(interimPart?" ":"")+phrase}if(finalPart){sessionFinal+=(sessionFinal?" ":"")+finalPart;lastInterim=""}else lastInterim=interimPart;finalText=sessionFinal;$("text").value=(sessionFinal+(lastInterim?" "+lastInterim:"")).trim()};rec.onerror=e=>{listening=false;$("mic").classList.remove("listening");$("mic").textContent="🎙️ Dictar";$("hint").textContent="Dictado detenido.";ui.notify(e.error==="not-allowed"?"Permiso de micrófono denegado":"Error de dictado: "+e.error)};rec.onend=()=>{finalText=sessionFinal;$("text").value=finalText;listening=false;$("mic").classList.remove("listening");$("mic").textContent="🎙️ Dictar";$("hint").textContent="Dictado terminado. Pulsa «Dictar» para continuar."};try{rec.start()}catch(e){listening=false;$("mic").classList.remove("listening");$("mic").textContent="🎙️ Dictar";ui.notify("No se pudo iniciar el dictado")}}
function readImages(files,msg){pendingImages=files;ui.showImagePreview(files);ui.notify(msg)}

$("mic").onclick=start;
$("clear").onclick=()=>{$("text").value="";finalText="";ui.notify("Texto borrado")};
$("contactsConnect").onclick=google.connectContacts;
$("contactsDisconnect").onclick=google.disconnectContacts;
$("calendarConnect").onclick=google.connectCalendar;
$("calendarDisconnect").onclick=google.disconnectCalendar;
$("resetData").onclick=async()=>{if(!confirm("Se eliminarán todas las entradas, imágenes y archivos guardados solo en este dispositivo. Google Sheets no se modificará. ¿Continuar?"))return;try{await deleteMediaDB();clearNotes();notes=[];pendingImages=[];pendingFiles=[];$("text").value="";$("preview").innerHTML="";render();ui.notify("Todos los datos locales han sido eliminados")}catch(e){ui.notify("No se pudieron eliminar todos los datos locales")}};
$("add").onclick=add;
$("cameraInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Foto preparada")};
$("photoInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Imagen seleccionada")};
$("fileInput").onchange=e=>{pendingFiles=[...e.target.files];if(pendingFiles.length)ui.notify("Archivo preparado")};
$("search").oninput=render;
$("typeFilter").onchange=e=>{selectedType=e.target.value;render()};
document.querySelectorAll(".filter").forEach(button=>button.onclick=()=>{selectedFilter=button.dataset.filter;document.querySelectorAll(".filter").forEach(item=>item.classList.toggle("active",item===button));render()});
$("list").onclick=async event=>{const button=event.target.closest("button");if(!button)return;const note=notes.find(item=>item.id===button.dataset.id);if(!note)return;if(button.dataset.a==="calendar"){await google.createCalendarEvent(note);return}if(button.dataset.a==="contact"){ui.notify("No hay número de teléfono en esta entrada");return}if(button.dataset.a==="search-contact"){await google.searchContact(note);return}if(button.dataset.a==="open-file"){try{const media=await getMedia(MEDIA_STORES.files,button.dataset.mediaId);if(!media)throw new Error();const url=URL.createObjectURL(media.blob);window.open(url,"_blank");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){ui.notify("No se pudo abrir el archivo")}return}if(button.dataset.a==="toggle"){note.status=note.status==="done"?"pending":"done";save();return}if(button.dataset.a==="delete"){const nextNotes=notes.filter(item=>item.id!==note.id);if(!save(nextNotes))return;google.clearContactResult(note.id);try{for(const id of note.images||[])await deleteMedia(MEDIA_STORES.images,id);for(const file of note.files||[])if(file.id)await deleteMedia(MEDIA_STORES.files,file.id)}catch(e){ui.notify("La entrada se borró, pero quedó algún medio sin eliminar")}}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=0.14",{updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{});
load();
