import{clearNotes,deleteMediaDB,readShortcuts,writeShortcuts}from"./storage.js?v=0.20.1";
import{classify,actionData}from"./classifier.js?v=0.20.1";
import{sendEntry}from"./sheets.js?v=0.20.1";
import{createUI}from"./ui.js?v=0.20.1";
import{createGoogleIntegration}from"./google.js?v=0.20.1";
import{interpret,remoteProvider}from"./ai.js?v=0.20.1";
import{entryTypeForIntent,planIntent}from"./intents.js?v=0.20.1";
import{calendarQueryRange,temporalData}from"./temporal.js?v=0.20.1";
import{normalizeFutureCall,normalizeReminderSchedule,scheduleFor}from"./schedule.js?v=0.20.1";
import{createCloudSync}from"./firebase.js?v=0.20.1";
import{createMediaService}from"./media.js?v=0.20.1";

let media;const ui=createUI({getMedia:(_,id)=>media.getMedia(id)});const $=ui.$;
let notes=[],rec=null,listening=false,finalText="",pendingImages=[],pendingFiles=[],selectedFilter="all",selectedType="all",shortcutCapture=false,saving=false;
const DEFAULT_SHORTCUTS=[
 {label:"🗓️ Hoy",command:"¿Qué tengo hoy?"},{label:"🗓️ Próxima semana",command:"¿Qué tengo la semana que viene?"},
 {label:"📞 Llamar contacto",prompt:"Di el nombre del contacto.",prefix:"Llama a ",dictate:true},{label:"＋ Nuevo evento",prompt:"Cuéntame el evento: fecha, hora y lugar."},
 {label:"⏰ Recordatorio",prompt:"¿Qué quieres que te recuerde y cuándo?"},{label:"✕ Cancelar evento",prompt:"¿Qué evento quieres cancelar?"}
];
let shortcuts=readShortcuts()||DEFAULT_SHORTCUTS;
function render(){ui.render({notes,selectedFilter,selectedType,google})}
function autosize(){const text=$("text");text.style.height="auto";text.style.height=Math.min(text.scrollHeight,78)+"px"}
function renderShortcuts(){$("shortcuts").innerHTML=shortcuts.map((shortcut,index)=>`<button class="shortcut" data-shortcut="${index}">${esc(shortcut.label)}</button>`).join("")+`<button class="shortcut add" id="shortcutAdd" aria-label="Crear acceso directo">＋</button>`}
function saveShortcuts(){writeShortcuts(shortcuts);renderShortcuts()}
function prepareShortcut(shortcut){if(shortcut.command){$("text").value=shortcut.command;autosize();add();return}const legacyCall=shortcut.label==="📞 Llamar contacto"?"Llama a ":"",prefix=shortcut.prefix||legacyCall;$("text").value=prefix;$("text").placeholder=shortcut.prompt||"Escribe o dicta tu instrucción…";autosize();openDraft();if(shortcut.dictate||legacyCall)setTimeout(start,120);else ui.notify(shortcut.prompt||"Completa la instrucción y pulsa Enviar")}
function createShortcut(initial=""){const command=prompt("Escribe la orden que ejecutará Angeli.",initial);if(!command?.trim())return;const label=prompt("Nombre corto para el acceso directo.",command.trim().slice(0,24));if(!label?.trim())return;shortcuts.push({label:label.trim(),command:command.trim()});saveShortcuts();ui.notify("Acceso directo creado")}
function editShortcuts(){if(!shortcuts.length){ui.notify("No hay accesos para editar");return}const choices=shortcuts.map((shortcut,index)=>`${index+1}. ${shortcut.label}`).join("\n"),value=prompt(`Indica el número del acceso que quieres eliminar:\n${choices}`);const index=Number(value)-1;if(!Number.isInteger(index)||!shortcuts[index])return;shortcuts.splice(index,1);saveShortcuts();ui.notify("Acceso directo eliminado")}
function scrollConversation(){requestAnimationFrame(()=>$("mainContent").scrollTo({top:$("mainContent").scrollHeight,behavior:"smooth"}))}
function setSending(active){["add","headerSend"].forEach(id=>{$(id).disabled=active});}
async function saveConfirmed(nextNotes,previousNotes=notes){if(!cloud.isSignedIn()){ui.notify("Inicia sesión en Angeli antes de guardar");return false}notes=nextNotes;render();ui.setSyncStatus({state:"pending"});try{await cloud.syncNotes(nextNotes,previousNotes);return true}catch(error){notes=previousNotes;render();ui.setSyncStatus({state:"error",error});ui.notify("No se pudo sincronizar la entrada. No se ha dado por guardada.");return false}}
function save(nextNotes,previousNotes=notes){void saveConfirmed(nextNotes,previousNotes);return true}
const cloud=createCloudSync({notify:ui.notify});
const google=createGoogleIntegration({notify:ui.notify,refresh:render,setStatus:ui.setGoogleStatus,saveNotes:save,getNotes:()=>notes,getAuthToken:cloud.getAuthToken,getSession:cloud.session});
media=createMediaService({getAuthToken:cloud.getAuthToken,ensureDrive:google.ensureDrive});
function openDraft(){ui.showDraft({value:$("text").value,onInput:value=>{$("text").value=value;finalText=value;autosize()},onSend:add,onCancel:ui.closeLayers})}
async function load(){notes=[];renderShortcuts();google.updateStatus();ui.setSyncStatus({state:"connecting"});render();await cloud.initialize({onRemoteNotes:remote=>{notes=remote;render()},onSyncStatus:ui.setSyncStatus,onAuthChange:async()=>{google.updateStatus();if(cloud.isSignedIn())await google.syncLinks();render()}});render()}
async function add(){if(saving)return;const text=$("text").value.trim();if(!text&&!pendingImages.length&&!pendingFiles.length){ui.notify("No hay nada que enviar");return}if(!cloud.isSignedIn()){ui.notify("Inicia sesión en Angeli antes de guardar");return}const now=new Date(),id=crypto.randomUUID(),images=[],files=[],hasMedia=Boolean(pendingImages.length||pendingFiles.length);saving=true;setSending(true);if(hasMedia)ui.showWorking("Guardando adjunto","Angeli está subiendo el archivo a Drive…","No pulses Enviar otra vez; te avisaré cuando termine.");try{for(const file of pendingImages){const item=await media.upload(file,"image",id);images.push(item)}for(const file of pendingFiles){const item=await media.upload(file,"file",id);files.push(item)}const fallbackType=classify(text,images,files),rawInterpretation=await interpret(text,{provider:value=>google.interpretWithAI(value,remoteProvider),fallback:()=>localInterpretation(text,fallbackType)}),interpretation=normalizeReminderSchedule(normalizeFutureCall(rawInterpretation,text),text,now),proposal=planIntent(interpretation,fallbackType),type=entryTypeForIntent(proposal,fallbackType),data=interpretation.source==="ai"?{...(interpretation.date?{scheduledDate:interpretation.date}:{}),...(interpretation.time?{scheduledTime:interpretation.time}:{}),...(interpretation.phone?{phone:interpretation.phone}:{}),...(interpretation.location?{location:interpretation.location}:{}),...(type==="calendar"&&interpretation.title?{calendarTitle:interpretation.title}:{}),...(type==="contact"&&interpretation.contactName?{contactQuery:interpretation.contactName}:{})}:actionData(text,type),schedule=scheduleFor(interpretation,text),entry={id,date:now.toISOString(),text,status:"pending",type,...data,aiIntent:interpretation,proposal,...(proposal.intent==="calendar.create"?{calendarStatus:"pending"}:{}),...(schedule?{schedule}:{}),images,files};if(!await saveConfirmed([entry,...notes])){ui.closeLayers();return}$("text").value="";$("text").placeholder="Escribe o dicta tu instrucción…";autosize();finalText="";pendingImages=[];pendingFiles=[];$("preview").innerHTML="";try{await sendEntry(entry,now);ui.notify("Entrada registrada en Google")}catch(e){ui.notify("Entrada sincronizada · Google Sheets no respondió")}ui.showEntryAction(entry,google)}catch(error){ui.closeLayers();ui.notify(error.message||"No se pudo guardar la entrada")}finally{saving=false;setSending(false)}}
function localInterpretation(text,type){const reminder=type==="reminder",data={...actionData(text,type),...temporalData(text,new Date(),{inferDateFromTime:reminder})},isCalendarQuery=/\b(?:qué|que)\s+(?:tengo|hay)|\b(?:muéstrame|muestrame|consulta)\s+(?:mi\s+)?(?:agenda|calendario)\b/i.test(text),futureCall=type==="contact"&&Boolean(data.scheduledDate&&data.scheduledTime),intent=isCalendarQuery?"calendar.query":futureCall?"reminder.create":{note:"note",task:"task.create",reminder:"reminder.create",calendar:"calendar.create",contact:"contact.call",file:"file.store",photo:"photo.store"}[type]||"note";return{intent,confidence:.5,title:text||null,date:data.scheduledDate||null,time:data.scheduledTime||null,...(isCalendarQuery?(calendarQueryRange(text)||{}):{}),location:null,contactName:data.contactQuery||null,phone:data.phone||null,notes:null,target:null,changes:null,requiresConfirmation:Boolean(data.scheduledDate&&data.scheduledTime)}}
function setMicState(active){$("mic").classList.toggle("listening",active);$("micMini").classList.toggle("listening",active);$("micLabel").textContent=active?"Escuchando… toca otra vez para parar":"Toca para hablar"}
function stop(){listening=false;if(rec){try{rec.stop()}catch(e){}}rec=null;setMicState(false);$("hint").textContent="Dictado terminado. Puedes continuar o pulsar Enviar cuando acabes.";autosize()}
function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){ui.notify("Este navegador no admite dictado");return}if(listening){stop();return}openDraft();finalText=$("text").value.trim();rec=new SR();rec.lang="es-ES";rec.continuous=false;rec.interimResults=true;rec.maxAlternatives=1;let sessionFinal=finalText||"",lastInterim="";rec.onstart=()=>{listening=true;setMicState(true);$("hint").textContent="Escuchando. Pulsa Enviar cuando la instrucción esté completa."};rec.onresult=e=>{let finalPart="",interimPart="";for(let i=e.resultIndex;i<e.results.length;i++){const result=e.results[i],phrase=(result[0]?.transcript||"").trim();if(!phrase)continue;if(result.isFinal)finalPart+=(finalPart?" ":"")+phrase;else interimPart+=(interimPart?" ":"")+phrase}if(finalPart){sessionFinal+=(sessionFinal?" ":"")+finalPart;lastInterim=""}else lastInterim=interimPart;finalText=sessionFinal;$("text").value=(sessionFinal+(lastInterim?" "+lastInterim:"")).trim();ui.updateDraft($("text").value);autosize()};rec.onerror=e=>{listening=false;setMicState(false);$("hint").textContent="Dictado detenido.";ui.notify(e.error==="not-allowed"?"Permiso de micrófono denegado":"Error de dictado: "+e.error)};rec.onend=()=>{finalText=sessionFinal;$("text").value=finalText;ui.updateDraft(finalText);listening=false;setMicState(false);$("hint").textContent="Dictado terminado. Puedes continuar o pulsar Enviar cuando acabes.";if(shortcutCapture&&finalText){shortcutCapture=false;createShortcut(finalText);$("text").value="";finalText=""}autosize()};try{rec.start()}catch(e){listening=false;setMicState(false);ui.notify("No se pudo iniciar el dictado")}}
function readImages(files,msg){pendingImages=files;ui.showImagePreview(files);ui.notify(msg)}

$("mic").onclick=start;$("micMini").onclick=start;
$("clear").onclick=()=>{$("text").value="";finalText="";autosize();ui.notify("Borrador limpiado")};
$("contactsConnect").onclick=google.connectContacts;
$("contactsDisconnect").onclick=google.disconnectContacts;
$("calendarConnect").onclick=google.connectCalendar;
$("calendarDisconnect").onclick=google.disconnectCalendar;
$("driveConnect").onclick=google.connectDrive;
$("driveDisconnect").onclick=google.disconnectDrive;
$("aiConnect").onclick=cloud.connect;
$("aiDisconnect").onclick=cloud.disconnect;
$("resetData").onclick=async()=>{if(!confirm("Se borrará únicamente la caché temporal de este dispositivo. Tus entradas y adjuntos seguirán en Angeli y se volverán a cargar. ¿Continuar?"))return;try{await deleteMediaDB();clearNotes();pendingImages=[];pendingFiles=[];$("text").value="";$("preview").innerHTML="";ui.notify("Caché local eliminada; tus datos siguen en Angeli")}catch(e){ui.notify("No se pudo eliminar toda la caché local")}};
$("add").onclick=add;
$("headerSend").onclick=add;
$("text").oninput=()=>{autosize();ui.updateDraft($("text").value)};
$("text").onfocus=()=>{if(!$("actionModal").classList.contains("show"))setTimeout(()=>{if(!$("actionModal").classList.contains("show"))openDraft()},120)};
$("text").onkeydown=event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();add()}};
$("attachToggle").onclick=()=>$("attachmentChoices").classList.toggle("show");
$("searchToggle").onclick=()=>$("searchPanel").classList.toggle("show");
$("menuOpen").onclick=ui.openMenu;$("menuClose").onclick=ui.closeLayers;$("scrim").onclick=ui.closeLayers;
$("clearView").onclick=()=>{if(confirm("Esto limpia solo la conversación visible. Tus entradas, fotos y archivos seguirán guardados. ¿Continuar?")){$("list").innerHTML='<div class="empty">Vista limpia. Tus datos siguen guardados.</div>';ui.notify("Vista limpiada")}};
$("shortcutManual").onclick=()=>createShortcut();
$("shortcutVoice").onclick=()=>{shortcutCapture=true;$("text").value="";$("text").placeholder="Di la orden que ejecutará el acceso directo…";ui.closeLayers();start()};
$("shortcutEdit").onclick=editShortcuts;
$("cameraInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Foto preparada")};
$("photoInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Imagen seleccionada")};
$("fileInput").onchange=e=>{pendingFiles=[...e.target.files];if(pendingFiles.length)ui.notify("Archivo preparado")};
$("search").oninput=render;
$("typeFilter").onchange=e=>{selectedType=e.target.value;render()};
document.querySelectorAll(".filter").forEach(button=>button.onclick=()=>{selectedFilter=button.dataset.filter;document.querySelectorAll(".filter").forEach(item=>item.classList.toggle("active",item===button));render()});
$("shortcuts").onclick=event=>{const button=event.target.closest("button");if(!button)return;if(button.id==="shortcutAdd"){createShortcut();return}const shortcut=shortcuts[Number(button.dataset.shortcut)];if(shortcut)prepareShortcut(shortcut)};
async function handleEntryAction(event){const button=event.target.closest("button");if(!button)return;const note=notes.find(item=>item.id===button.dataset.id);if(!note)return;if(button.dataset.a==="show-action"){ui.showEntryAction(note,google);return}if(button.dataset.a==="schedule"){ui.showWorking("Programando aviso","Angeli está creando el aviso en Calendar…","");await google.createScheduledReminder(note);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="cancel-schedule"){await google.cancelScheduledReminder(note);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="calendar"){ui.showWorking("Añadiendo al calendario","Angeli está creando el evento…","");await google.createCalendarEvent(note,{confirmed:true});ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="search-calendar"){ui.showWorking("Buscando en Calendar","Angeli está revisando tus eventos…","");await google.searchCalendar(note);ui.showEntryAction(note,google);return}if(button.dataset.a==="calendar-delete"){await google.deleteCalendarEvent(note,button.dataset.eventId);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="calendar-update"){await google.updateCalendarEvent(note,button.dataset.eventId);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="call"){ui.closeLayers();window.location.href=`tel:${button.dataset.phone}`;return}if(button.dataset.a==="search-contact"){ui.showWorking("Buscando contacto","Angeli está buscando a "+(note.contactQuery||"ese contacto")+"…","");await google.searchContact(note);ui.showEntryAction(note,google);return}if(button.dataset.a==="open-file"){try{const media=await mediaServiceGet(button.dataset.mediaId);if(!media)throw new Error();const url=URL.createObjectURL(media.blob);window.open(url,"_blank");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){ui.notify("No se pudo abrir el archivo")}return}if(button.dataset.a==="toggle"){const nextNotes=notes.map(item=>item.id===note.id?{...item,status:item.status==="done"?"pending":"done"}:item);save(nextNotes);return}if(button.dataset.a==="delete"){const nextNotes=notes.filter(item=>item.id!==note.id);if(!save(nextNotes))return;google.clearContactResult(note.id);try{for(const image of note.images||[])await media.remove(typeof image==="string"?image:image.driveFileId||image.id);for(const file of note.files||[])if(file.id||file.driveFileId)await media.remove(file.driveFileId||file.id)}catch(e){ui.notify("La entrada se borró, pero quedó algún adjunto en Drive")}}}
$("list").onclick=handleEntryAction;$("actionModal").onclick=handleEntryAction;
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=0.20.1",{updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{});
load();

async function mediaServiceGet(id){return media.getMedia(id)}
function esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
