import{MEDIA_STORES,readNotes,writeNotes,clearNotes,migrateLegacyImages,putMedia,getMedia,deleteMedia,deleteMediaDB,readShortcuts,writeShortcuts}from"./storage.js?v=0.19.0";
import{classify,actionData}from"./classifier.js?v=0.19.0";
import{sendEntry}from"./sheets.js?v=0.19.0";
import{createUI}from"./ui.js?v=0.19.0";
import{createGoogleIntegration}from"./google.js?v=0.19.0";
import{interpret,remoteProvider}from"./ai.js?v=0.19.0";
import{entryTypeForIntent,planIntent}from"./intents.js?v=0.19.0";
import{calendarQueryRange,temporalData}from"./temporal.js?v=0.19.0";
import{normalizeFutureCall,normalizeReminderSchedule,scheduleFor}from"./schedule.js?v=0.19.0";
import{createCloudSync}from"./firebase.js?v=0.19.0";

const ui=createUI({getMedia:(store,id)=>getMedia(store,id)});const $=ui.$;
let notes=[],rec=null,listening=false,finalText="",pendingImages=[],pendingFiles=[],selectedFilter="all",selectedType="all",shortcutCapture=false;
const DEFAULT_SHORTCUTS=[
 {label:"🗓️ Hoy",command:"¿Qué tengo hoy?"},{label:"🗓️ Próxima semana",command:"¿Qué tengo la semana que viene?"},
 {label:"📞 Llamar contacto",prompt:"Di el nombre del contacto.",prefix:"Llama a ",dictate:true},{label:"＋ Nuevo evento",prompt:"Cuéntame el evento: fecha, hora y lugar."},
 {label:"⏰ Recordatorio",prompt:"¿Qué quieres que te recuerde y cuándo?"},{label:"✕ Cancelar evento",prompt:"¿Qué evento quieres cancelar?"}
];
let shortcuts=readShortcuts()||DEFAULT_SHORTCUTS;
function render(){ui.render({notes,selectedFilter,selectedType,google})}
function autosize(){const text=$("text");text.style.height="auto";text.style.height=Math.min(text.scrollHeight,78)+"px"}
function renderShortcuts(){$("shortcuts").innerHTML=shortcuts.map((shortcut,index)=>`<button class="shortcut" data-shortcut="${index}">${esc(shortcut.label)}</button>`).join("")+`<button class="shortcut add" id="shortcutAdd" aria-label="Crear acceso directo">＋</button>`}
function saveShortcuts(){writeShortcuts(shortcuts);renderShortcuts()}
function prepareShortcut(shortcut){if(shortcut.command){$("text").value=shortcut.command;autosize();add();return}const legacyCall=shortcut.label==="📞 Llamar contacto"?"Llama a ":"",prefix=shortcut.prefix||legacyCall;$("text").value=prefix;$("text").placeholder=shortcut.prompt||"Escribe o dicta tu instrucción…";autosize();openDraft();if(shortcut.dictate||legacyCall)setTimeout(start,120);else ui.notify(shortcut.prompt||"Completa la instrucción y pulsa Enviar")}
function createShortcut(initial=""){const command=prompt("Escribe la orden que ejecutará Angeli.",initial);if(!command?.trim())return;const label=prompt("Nombre corto para el acceso directo.",command.trim().slice(0,24));if(!label?.trim())return;shortcuts.push({label:label.trim(),command:command.trim()});saveShortcuts();ui.notify("Acceso directo creado")}
function editShortcuts(){if(!shortcuts.length){ui.notify("No hay accesos para editar");return}const choices=shortcuts.map((shortcut,index)=>`${index+1}. ${shortcut.label}`).join("\n"),value=prompt(`Indica el número del acceso que quieres eliminar:\n${choices}`);const index=Number(value)-1;if(!Number.isInteger(index)||!shortcuts[index])return;shortcuts.splice(index,1);saveShortcuts();ui.notify("Acceso directo eliminado")}
function scrollConversation(){requestAnimationFrame(()=>$("mainContent").scrollTo({top:$("mainContent").scrollHeight,behavior:"smooth"}))}
function save(nextNotes=notes){try{const previous=notes;writeNotes(nextNotes);notes=nextNotes;render();cloud.syncNotes(nextNotes,previous).catch(()=>ui.notify("Guardado en este dispositivo · se sincronizará al recuperar conexión"));return true}catch(e){ui.notify(e.name==="QuotaExceededError"?"No hay espacio para guardar la foto. Reduce o elimina entradas con imágenes.":"No se pudo guardar la entrada");return false}}
const cloud=createCloudSync({notify:ui.notify});
const google=createGoogleIntegration({notify:ui.notify,refresh:render,setStatus:ui.setGoogleStatus,saveNotes:save,getNotes:()=>notes,getAuthToken:cloud.getAuthToken,getSession:cloud.session});
function openDraft(){ui.showDraft({value:$("text").value,onInput:value=>{$("text").value=value;finalText=value;autosize()},onSend:add,onCancel:ui.closeLayers})}
async function load(){notes=readNotes();if(await migrateLegacyImages(notes))save(notes);let changed=false;notes=notes.map(note=>{const detectedType=classify(note.text,note.images||[],note.files||[]),shouldReclassify=!note.type||(note.type==="note"&&detectedType==="calendar"),type=shouldReclassify?detectedType:note.type,data=actionData(note.text,type),location=note.location||note.aiIntent?.location||null,calendarTitle=note.calendarTitle||note.aiIntent?.title||null,legacySchedule=!note.schedule&&type==="reminder"?scheduleFor(normalizeReminderSchedule(note.aiIntent||{intent:"reminder.create",date:note.scheduledDate||null,time:note.scheduledTime||null,contactName:note.contactQuery||null,phone:note.phone||null},note.text),note.text):null;if(type==="calendar"&&!note.calendarStatus)data.calendarStatus="pending";const needsData=shouldReclassify||Object.entries(data).some(([key,value])=>note[key]!==value)||Boolean(location)&&note.location!==location||Boolean(calendarTitle)&&note.calendarTitle!==calendarTitle||Boolean(legacySchedule);if(!needsData)return note;changed=true;return{...note,type,...data,...(location?{location}:{}),...(calendarTitle?{calendarTitle}:{}),...(legacySchedule?{schedule:legacySchedule}:{})}});if(changed)save(notes);renderShortcuts();google.updateStatus();render();await cloud.initialize({getLocalNotes:()=>notes,onRemoteNotes:(remote,{bootstrapping})=>{const localById=new Map(notes.map(note=>[note.id,note]));const remoteById=new Map(remote.map(note=>[note.id,note]));const combined=bootstrapping?[...remote,...notes.filter(note=>!remoteById.has(note.id))]:remote;notes=combined;writeNotes(notes);render()},onAuthChange:async()=>{google.updateStatus();if(cloud.isSignedIn())await google.syncLinks();render()}});render()}
async function add(){const text=$("text").value.trim();if(!text&&!pendingImages.length&&!pendingFiles.length){ui.notify("No hay nada que enviar");return}const now=new Date(),id=crypto.randomUUID(),images=[],files=[];try{for(const file of pendingImages){const mediaId=crypto.randomUUID();await putMedia(MEDIA_STORES.images,{id:mediaId,blob:file,type:file.type,size:file.size});images.push(mediaId)}for(const file of pendingFiles){const mediaId=crypto.randomUUID();await putMedia(MEDIA_STORES.files,{id:mediaId,blob:file,type:file.type,size:file.size});files.push({id:mediaId,name:file.name,type:file.type,size:file.size})}}catch(e){ui.notify("No se pudieron guardar los archivos o imágenes");return}const fallbackType=classify(text,images,files),rawInterpretation=await interpret(text,{provider:value=>google.interpretWithAI(value,remoteProvider),fallback:()=>localInterpretation(text,fallbackType)}),interpretation=normalizeReminderSchedule(normalizeFutureCall(rawInterpretation,text),text,now),proposal=planIntent(interpretation,fallbackType),type=entryTypeForIntent(proposal,fallbackType),data=interpretation.source==="ai"?{...(interpretation.date?{scheduledDate:interpretation.date}:{}),...(interpretation.time?{scheduledTime:interpretation.time}:{}),...(interpretation.phone?{phone:interpretation.phone}:{}),...(interpretation.location?{location:interpretation.location}:{}),...(type==="calendar"&&interpretation.title?{calendarTitle:interpretation.title}:{}),...(type==="contact"&&interpretation.contactName?{contactQuery:interpretation.contactName}:{})}:actionData(text,type),schedule=scheduleFor(interpretation,text),entry={id,date:now.toISOString(),text,status:"pending",type,...data,aiIntent:interpretation,proposal,...(proposal.intent==="calendar.create"?{calendarStatus:"pending"}:{}),...(schedule?{schedule}:{}),images,files};if(!save([entry,...notes])){try{await Promise.all([...images.map(mediaId=>deleteMedia(MEDIA_STORES.images,mediaId)),...files.map(file=>deleteMedia(MEDIA_STORES.files,file.id))])}catch(e){}return}$("text").value="";$("text").placeholder="Escribe o dicta tu instrucción…";autosize();finalText="";pendingImages=[];pendingFiles=[];$("preview").innerHTML="";try{await sendEntry(entry,now);ui.notify("Entrada registrada en Google")}catch(e){ui.notify("Guardada localmente · Google no respondió")}ui.showEntryAction(entry,google)}
function localInterpretation(text,type){const reminder=type==="reminder",data={...actionData(text,type),...temporalData(text,new Date(),{inferDateFromTime:reminder})},isCalendarQuery=/\b(?:qué|que)\s+(?:tengo|hay)|\b(?:muéstrame|muestrame|consulta)\s+(?:mi\s+)?(?:agenda|calendario)\b/i.test(text),futureCall=type==="contact"&&Boolean(data.scheduledDate&&data.scheduledTime),intent=isCalendarQuery?"calendar.query":futureCall?"reminder.create":{note:"note",task:"task.create",reminder:"reminder.create",calendar:"calendar.create",contact:"contact.call",file:"file.store",photo:"photo.store"}[type]||"note";return{intent,confidence:.5,title:text||null,date:data.scheduledDate||null,time:data.scheduledTime||null,...(isCalendarQuery?(calendarQueryRange(text)||{}):{}),location:null,contactName:data.contactQuery||null,phone:data.phone||null,notes:null,target:null,changes:null,requiresConfirmation:Boolean(data.scheduledDate&&data.scheduledTime)}}
function setMicState(active){$("mic").classList.toggle("listening",active);$("micMini").classList.toggle("listening",active);$("micLabel").textContent=active?"Escuchando… toca otra vez para parar":"Toca para hablar"}
function stop(){listening=false;if(rec){try{rec.stop()}catch(e){}}rec=null;setMicState(false);$("hint").textContent="Dictado terminado. Puedes continuar o pulsar Enviar cuando acabes.";autosize()}
function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){ui.notify("Este navegador no admite dictado");return}if(listening){stop();return}openDraft();finalText=$("text").value.trim();rec=new SR();rec.lang="es-ES";rec.continuous=false;rec.interimResults=true;rec.maxAlternatives=1;let sessionFinal=finalText||"",lastInterim="";rec.onstart=()=>{listening=true;setMicState(true);$("hint").textContent="Escuchando. Pulsa Enviar cuando la instrucción esté completa."};rec.onresult=e=>{let finalPart="",interimPart="";for(let i=e.resultIndex;i<e.results.length;i++){const result=e.results[i],phrase=(result[0]?.transcript||"").trim();if(!phrase)continue;if(result.isFinal)finalPart+=(finalPart?" ":"")+phrase;else interimPart+=(interimPart?" ":"")+phrase}if(finalPart){sessionFinal+=(sessionFinal?" ":"")+finalPart;lastInterim=""}else lastInterim=interimPart;finalText=sessionFinal;$("text").value=(sessionFinal+(lastInterim?" "+lastInterim:"")).trim();ui.updateDraft($("text").value);autosize()};rec.onerror=e=>{listening=false;setMicState(false);$("hint").textContent="Dictado detenido.";ui.notify(e.error==="not-allowed"?"Permiso de micrófono denegado":"Error de dictado: "+e.error)};rec.onend=()=>{finalText=sessionFinal;$("text").value=finalText;ui.updateDraft(finalText);listening=false;setMicState(false);$("hint").textContent="Dictado terminado. Puedes continuar o pulsar Enviar cuando acabes.";if(shortcutCapture&&finalText){shortcutCapture=false;createShortcut(finalText);$("text").value="";finalText=""}autosize()};try{rec.start()}catch(e){listening=false;setMicState(false);ui.notify("No se pudo iniciar el dictado")}}
function readImages(files,msg){pendingImages=files;ui.showImagePreview(files);ui.notify(msg)}

$("mic").onclick=start;$("micMini").onclick=start;
$("clear").onclick=()=>{$("text").value="";finalText="";autosize();ui.notify("Borrador limpiado")};
$("contactsConnect").onclick=google.connectContacts;
$("contactsDisconnect").onclick=google.disconnectContacts;
$("calendarConnect").onclick=google.connectCalendar;
$("calendarDisconnect").onclick=google.disconnectCalendar;
$("aiConnect").onclick=cloud.connect;
$("aiDisconnect").onclick=cloud.disconnect;
$("resetData").onclick=async()=>{if(!confirm("Se eliminarán todas las entradas, imágenes y archivos guardados solo en este dispositivo. Google Sheets no se modificará. ¿Continuar?"))return;try{await deleteMediaDB();clearNotes();notes=[];pendingImages=[];pendingFiles=[];$("text").value="";$("preview").innerHTML="";render();ui.notify("Todos los datos locales han sido eliminados")}catch(e){ui.notify("No se pudieron eliminar todos los datos locales")}};
$("add").onclick=add;
$("headerSend").onclick=add;
$("text").oninput=()=>{autosize();ui.updateDraft($("text").value)};
$("text").onfocus=()=>{if(!$("actionModal").classList.contains("show"))setTimeout(()=>{if(!$("actionModal").classList.contains("show"))openDraft()},120)};
$("text").onkeydown=event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();add()}};
$("attachToggle").onclick=()=>$("attachmentChoices").classList.toggle("show");
$("searchToggle").onclick=()=>$("searchPanel").classList.toggle("show");
$("menuOpen").onclick=ui.openMenu;$("menuClose").onclick=ui.closeLayers;$("scrim").onclick=ui.closeLayers;
$("clearView").onclick=()=>{if(confirm("Esto limpia solo la conversación visible. Tus entradas, fotos y archivos seguirán guardados. ¿Continuar?")){$("list").innerHTML='<div class="empty">Vista limpia. Tus datos siguen guardados.</div>';ui.notify("Vista limpiada")}};
$("shortcutManual").onclick=()=>createShortcut();
$("shortcutVoice").onclick=()=>{shortcutCapture=true;$("text").value="";$("text").placeholder="Di la orden que ejecutará el acceso directo…";ui.closeLayers();start()};
$("shortcutEdit").onclick=editShortcuts;
$("cameraInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Foto preparada")};
$("photoInput").onchange=e=>{if(e.target.files.length)readImages([...e.target.files],"Imagen seleccionada")};
$("fileInput").onchange=e=>{pendingFiles=[...e.target.files];if(pendingFiles.length)ui.notify("Archivo preparado")};
$("search").oninput=render;
$("typeFilter").onchange=e=>{selectedType=e.target.value;render()};
document.querySelectorAll(".filter").forEach(button=>button.onclick=()=>{selectedFilter=button.dataset.filter;document.querySelectorAll(".filter").forEach(item=>item.classList.toggle("active",item===button));render()});
$("shortcuts").onclick=event=>{const button=event.target.closest("button");if(!button)return;if(button.id==="shortcutAdd"){createShortcut();return}const shortcut=shortcuts[Number(button.dataset.shortcut)];if(shortcut)prepareShortcut(shortcut)};
async function handleEntryAction(event){const button=event.target.closest("button");if(!button)return;const note=notes.find(item=>item.id===button.dataset.id);if(!note)return;if(button.dataset.a==="show-action"){ui.showEntryAction(note,google);return}if(button.dataset.a==="schedule"){ui.showWorking("Programando aviso","Angeli está creando el aviso en Calendar…","");await google.createScheduledReminder(note);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="cancel-schedule"){await google.cancelScheduledReminder(note);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="calendar"){ui.showWorking("Añadiendo al calendario","Angeli está creando el evento…","");await google.createCalendarEvent(note,{confirmed:true});ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="search-calendar"){ui.showWorking("Buscando en Calendar","Angeli está revisando tus eventos…","");await google.searchCalendar(note);ui.showEntryAction(note,google);return}if(button.dataset.a==="calendar-delete"){await google.deleteCalendarEvent(note,button.dataset.eventId);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="calendar-update"){await google.updateCalendarEvent(note,button.dataset.eventId);ui.showEntryAction(notes.find(item=>item.id===note.id)||note,google);return}if(button.dataset.a==="call"){ui.closeLayers();window.location.href=`tel:${button.dataset.phone}`;return}if(button.dataset.a==="search-contact"){ui.showWorking("Buscando contacto","Angeli está buscando a "+(note.contactQuery||"ese contacto")+"…","");await google.searchContact(note);ui.showEntryAction(note,google);return}if(button.dataset.a==="open-file"){try{const media=await getMedia(MEDIA_STORES.files,button.dataset.mediaId);if(!media)throw new Error();const url=URL.createObjectURL(media.blob);window.open(url,"_blank");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){ui.notify("No se pudo abrir el archivo")}return}if(button.dataset.a==="toggle"){note.status=note.status==="done"?"pending":"done";save();return}if(button.dataset.a==="delete"){const nextNotes=notes.filter(item=>item.id!==note.id);if(!save(nextNotes))return;google.clearContactResult(note.id);try{for(const id of note.images||[])await deleteMedia(MEDIA_STORES.images,id);for(const file of note.files||[])if(file.id)await deleteMedia(MEDIA_STORES.files,file.id)}catch(e){ui.notify("La entrada se borró, pero quedó algún medio sin eliminar")}}}
$("list").onclick=handleEntryAction;$("actionModal").onclick=handleEntryAction;
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=0.19.0",{updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{});
load();

function esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
