import{cleanTemporalText}from"./temporal.js?v=0.16.5";

const GOOGLE_CLIENT_ID="172772694205-7sigc4s8lkhebs4dtjjvj6huptj10tt0.apps.googleusercontent.com";
const GOOGLE_CONTACTS_SCOPE="https://www.googleapis.com/auth/contacts.readonly";
const GOOGLE_CALENDAR_SCOPE="https://www.googleapis.com/auth/calendar.events";
const CALENDAR_ACTIONS=new Set(["calendar.query","calendar.update","calendar.delete"]);

export function createGoogleIntegration({notify,refresh,setStatus,saveNotes,getNotes}){
 let contactsToken="",contactsExpiresAt=0,calendarToken="",calendarExpiresAt=0,contactsExpired=false,calendarExpired=false,identityPromise=null;
 let aiIdToken="",aiExpiresAt=0,aiAccount="",aiExpired=false;
 const contactResults=new Map(),calendarResults=new Map(),calendarInFlight=new Set();
 function contactsValid(){if(contactsToken&&Date.now()<contactsExpiresAt)return true;if(contactsToken)contactsExpired=true;contactsToken="";contactsExpiresAt=0;return false}
 function calendarValid(){if(calendarToken&&Date.now()<calendarExpiresAt)return true;if(calendarToken)calendarExpired=true;calendarToken="";calendarExpiresAt=0;return false}
 function aiValid(){if(aiIdToken&&Date.now()<aiExpiresAt)return true;if(aiIdToken)aiExpired=true;aiIdToken="";aiExpiresAt=0;aiAccount="";return false}
 function updateStatus(){if(!GOOGLE_CLIENT_ID){setStatus({contacts:"Contactos sin configurar",calendar:"Calendario sin configurar",ai:"IA sin configurar"});return}setStatus({contacts:contactsValid()?"Contactos conectados en esta sesión":contactsExpired?"Contactos: autorización caducada":"Contactos no conectados",calendar:calendarValid()?"Calendario conectado en esta sesión":calendarExpired?"Calendario: autorización caducada":"Calendario no conectado",ai:aiValid()?`IA conectada${aiAccount?` · ${aiAccount}`:""}`:aiExpired?"IA: autorización caducada":"IA no conectada"})}
 function loadIdentity(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(identityPromise)return identityPromise;identityPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://accounts.google.com/gsi/client";script.async=true;script.defer=true;script.onload=()=>window.google?.accounts?.oauth2?resolve():reject(new Error("Google Identity no se pudo iniciar"));script.onerror=()=>reject(new Error("No se pudo cargar Google Identity"));document.head.append(script)});return identityPromise}
 async function requestToken(scope,setToken){await loadIdentity();await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope,callback:response=>{if(response.error){reject(new Error(response.error));return}setToken(response);resolve()},error_callback:error=>reject(new Error(error.type||"No se pudo autorizar Google"))});client.requestAccessToken({prompt:"select_account"})})}
 async function connectContacts(){if(!GOOGLE_CLIENT_ID){notify("Google Contacts aún no está configurado");return false}try{await requestToken(GOOGLE_CONTACTS_SCOPE,response=>{contactsToken=response.access_token;contactsExpiresAt=expiresAt(response);contactsExpired=false});updateStatus();notify("Contactos conectados para esta sesión");return true}catch(e){updateStatus();notify("No se pudo conectar Contactos");return false}}
 async function connectCalendar(){if(!GOOGLE_CLIENT_ID){notify("Google Calendar aún no está configurado");return false}try{await requestToken(GOOGLE_CALENDAR_SCOPE,response=>{calendarToken=response.access_token;calendarExpiresAt=expiresAt(response);calendarExpired=false});updateStatus();notify("Calendario conectado para esta sesión");return true}catch(e){updateStatus();notify("No se pudo conectar Calendario");return false}}
 async function connectAI(){if(!GOOGLE_CLIENT_ID){notify("La IA aún no está configurada");return false}if(aiValid()){updateStatus();return true}try{await loadIdentity();await new Promise((resolve,reject)=>{let settled=false,displayTimeout=setTimeout(()=>fail("No se mostró la conexión de Google"),10000),fail=message=>{if(settled)return;settled=true;clearTimeout(displayTimeout);reject(new Error(message))};google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,auto_select:false,cancel_on_tap_outside:true,callback:response=>{if(settled)return;try{const payload=decodeGoogleCredential(response.credential);if(payload.aud!==GOOGLE_CLIENT_ID||!payload.exp)throw new Error("Credencial de Google no válida");aiIdToken=response.credential;aiExpiresAt=Number(payload.exp)*1000-30000;aiAccount=typeof payload.email==="string"?payload.email:"";aiExpired=false;settled=true;clearTimeout(displayTimeout);resolve()}catch(e){fail("No se pudo verificar la conexión de Google")}}});google.accounts.id.prompt(notification=>{if(notification.isNotDisplayed()||notification.isSkippedMoment())fail("Google no mostró la conexión")})});updateStatus();notify("IA conectada para esta sesión");return true}catch(e){updateStatus();notify("No se pudo conectar la IA");return false}}
 function disconnectContacts(){contactsToken="";contactsExpiresAt=0;contactsExpired=false;contactResults.clear();updateStatus();refresh();notify("Contactos desconectados de esta sesión")}
 function disconnectCalendar(){calendarToken="";calendarExpiresAt=0;calendarExpired=false;calendarResults.clear();updateStatus();refresh();notify("Calendario desconectado de esta sesión")}
 function disconnectAI(){aiIdToken="";aiExpiresAt=0;aiAccount="";aiExpired=false;updateStatus();notify("IA desconectada de esta sesión")}
 async function interpretWithAI(text,provider){if(!aiValid())throw new Error("IA sin conexión");return provider(text,aiIdToken)}
 async function searchContact(note){const query=note.contactQuery;if(!query){notify("No hay un nombre de contacto para buscar");return}if(!contactsValid()&&!(await connectContacts())){contactResults.set(note.id,{contacts:[],error:"No se pudo conectar Contactos con la cuenta de tu agenda."});updateStatus();refresh();return}const url=value=>`https://people.googleapis.com/v1/people:searchContacts?${new URLSearchParams({query:value,readMask:"names,phoneNumbers",pageSize:"10",sources:"READ_SOURCE_TYPE_CONTACT"})}`,request=value=>fetch(url(value),{headers:{Authorization:`Bearer ${contactsToken}`}});try{const warmup=await request("");if(!warmup.ok)throw new Error(String(warmup.status));const response=await request(query);if(!response.ok)throw new Error(String(response.status));const data=await response.json(),contacts=(data.results||[]).map(result=>result.person||{}).map(person=>({name:person.names?.[0]?.displayName||query,phones:(person.phoneNumbers||[]).map(contactPhoneValue).filter(Boolean)}));contactResults.set(note.id,{contacts});refresh()}catch(e){if(e.message==="401"||e.message==="403"){contactsToken="";contactsExpiresAt=0;contactsExpired=true;updateStatus()}contactResults.set(note.id,{contacts:[],error:"No se pudo consultar los contactos. Conecta Contactos de nuevo con la cuenta correcta."});refresh()}}
 async function createCalendarEvent(note,{confirmed=false}={}){if(note.calendarStatus==="synced"&&note.calendarEventId){notify("Esta entrada ya está añadida al calendario");return}if(!note.scheduledDate){notify("Falta la fecha para crear el evento");return}if(!note.scheduledTime){notify("Falta la hora para crear el evento");return}if(calendarInFlight.has(note.id))return;const start=calendarDateTime(note.scheduledDate,note.scheduledTime),display=new Date(start).toLocaleString("es-ES",{dateStyle:"medium",timeStyle:"short"}),title=calendarEventTitle(note),locationLine=note.location?`\nUbicación: ${note.location}`:"";if(!confirmed&&!confirm(`¿Añadir al calendario?\n${title}\n${display}${locationLine}`))return;calendarInFlight.add(note.id);let eventCreated=false;try{if(!calendarValid()&&!(await connectCalendar()))return;const eventId=note.calendarEventId||calendarEventKey(note),endpoint="https://www.googleapis.com/calendar/v3/calendars/primary/events",eventBody={id:eventId,summary:title,start:{dateTime:start,timeZone:"Europe/Madrid"},end:{dateTime:calendarEndDateTime(note.scheduledDate,note.scheduledTime),timeZone:"Europe/Madrid"},...(note.location?{location:note.location}:{})},response=await fetch(endpoint,{method:"POST",headers:calendarHeaders(),body:JSON.stringify(eventBody)});let event=response;if(response.status===409)event=await fetch(`${endpoint}/${encodeURIComponent(eventId)}`,{headers:calendarHeaders()});if(!event.ok)throw new Error(String(event.status));const saved=await event.json();eventCreated=true;if(!saveNotes(getNotes().map(item=>item.id===note.id?{...item,calendarStatus:"synced",calendarEventId:saved.id||eventId,calendarUrl:saved.htmlLink||""}:item))){notify("El evento se creó, pero no se pudo marcar localmente. Reintenta sin crear duplicados.");return}notify("Evento añadido al calendario")}catch(e){handleCalendarError(e);if(!eventCreated){saveNotes(getNotes().map(item=>item.id===note.id?{...item,calendarStatus:"error"}:item));notify("No se pudo añadir el evento al calendario")}}finally{calendarInFlight.delete(note.id)}}
 async function searchCalendar(note){const intent=note.proposal?.intent;if(!CALENDAR_ACTIONS.has(intent))return;if(!calendarValid()&&!(await connectCalendar())){calendarResults.set(note.id,{events:[],error:"Conecta Calendar con la cuenta donde están tus eventos."});refresh();return}const interpretation=note.aiIntent||{},target=interpretation.target||{},query=target.title||interpretation.title||"",range=intent==="calendar.query"?calendarRange(null,interpretation.rangeStart,interpretation.rangeEnd):calendarRange(target.date||null);try{const params=new URLSearchParams({singleEvents:"true",orderBy:"startTime",maxResults:"20",timeMin:range.from.toISOString(),timeMax:range.to.toISOString()});if(query)params.set("q",query);const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?${params}`,{headers:calendarHeaders()});if(!response.ok)throw new Error(String(response.status));const data=await response.json(),events=(data.items||[]).filter(event=>event.status!=="cancelled").map(calendarCandidate);calendarResults.set(note.id,{events,query});refresh()}catch(e){handleCalendarError(e);calendarResults.set(note.id,{events:[],error:"No se pudo consultar Calendar. Conéctalo de nuevo e inténtalo."});refresh()}}
 async function deleteCalendarEvent(note,eventId){const event=findCalendarResult(note.id,eventId);if(!event)return;if(!confirm(`¿Cancelar definitivamente este evento?\n${event.summary}\n${event.when}`))return;try{if(!calendarValid()&&!(await connectCalendar()))return;const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(eventId)}`,{method:"DELETE",headers:calendarHeaders()});if(!response.ok&&response.status!==410)throw new Error(String(response.status));completeCalendarAction(note,eventId,"delete");notify("Evento cancelado en Google Calendar")}catch(e){handleCalendarError(e);notify("No se pudo cancelar el evento")}}
 async function updateCalendarEvent(note,eventId){const event=findCalendarResult(note.id,eventId),changes=note.aiIntent?.changes;if(!event||!changes){notify("No hay cambios concretos para aplicar");return}const body=calendarPatch(event,changes);if(!Object.keys(body).length){notify("No hay cambios concretos para aplicar");return}if(!confirm(`¿Aplicar estos cambios a este evento?\n${event.summary}\n${event.when}`))return;try{if(!calendarValid()&&!(await connectCalendar()))return;const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(eventId)}`,{method:"PATCH",headers:calendarHeaders(),body:JSON.stringify(body)});if(!response.ok)throw new Error(String(response.status));const updated=await response.json();completeCalendarAction(note,eventId,"update",updated,changes);notify("Evento actualizado en Google Calendar")}catch(e){handleCalendarError(e);notify("No se pudo actualizar el evento")}}
 function completeCalendarAction(note,eventId,action,updated,changes){calendarResults.delete(note.id);saveNotes(getNotes().map(item=>{const request=item.id===note.id?{...item,proposal:{...item.proposal,actionStatus:"completed"}}:item;if(request.calendarEventId!==eventId)return request;if(action==="delete")return{...request,calendarStatus:"cancelled",calendarUrl:""};const data={...request,calendarStatus:"synced",calendarUrl:updated?.htmlLink||request.calendarUrl||""};if(changes?.title)data.calendarTitle=changes.title;if(changes?.location)data.location=changes.location;if(changes?.date)data.scheduledDate=changes.date;if(changes?.time)data.scheduledTime=changes.time;return data}));refresh()}
 function calendarHeaders(){return{Authorization:`Bearer ${calendarToken}`,"Content-Type":"application/json"}}
 function findCalendarResult(noteId,eventId){return calendarResults.get(noteId)?.events?.find(event=>event.id===eventId)||null}
 function handleCalendarError(error){if(error?.message==="401"||error?.message==="403"){calendarToken="";calendarExpiresAt=0;calendarExpired=true;updateStatus()}}
 function getContactResult(id){return contactResults.get(id)}
 function getCalendarResult(id){return calendarResults.get(id)}
 function clearContactResult(id){contactResults.delete(id)}
 return{updateStatus,connectContacts,connectCalendar,connectAI,disconnectContacts,disconnectCalendar,disconnectAI,interpretWithAI,searchContact,createCalendarEvent,searchCalendar,deleteCalendarEvent,updateCalendarEvent,getContactResult,getCalendarResult,clearContactResult,contactTel}
}

function expiresAt(response){return Date.now()+Math.max(0,Number(response.expires_in||0)-30)*1000}
function decodeGoogleCredential(credential){const part=(credential||"").split(".")[1];if(!part)throw new Error("Credencial no válida");const base64=part.replace(/-/g,"+").replace(/_/g,"/");const json=atob(base64+"=".repeat((4-base64.length%4)%4));return JSON.parse(json)}
function contactPhoneValue(phone){return(phone?.value||"").trim()}
function contactTel(phone){return contactPhoneValue({value:phone}).replace(/[^\d+]/g,"")}
function calendarEventTitle(note){return(note.calendarTitle||note.aiIntent?.title||cleanTemporalText(note.text)).trim()}
function calendarDateTime(date,time){return`${date}T${time}:00`}
function calendarEndDateTime(date,time){const end=new Date(calendarDateTime(date,time));end.setHours(end.getHours()+1);return`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,"0")}-${String(end.getDate()).padStart(2,"0")}T${String(end.getHours()).padStart(2,"0")}:${String(end.getMinutes()).padStart(2,"0")}:00`}
function calendarEventKey(note){return`angeli${note.id.replace(/-/g,"")}`}
function calendarRange(date,rangeStart,rangeEnd){if(rangeStart&&rangeEnd)return{from:new Date(`${rangeStart}T00:00:00`),to:new Date(`${rangeEnd}T00:00:00`)};if(date){const from=new Date(`${date}T00:00:00`),to=new Date(from);to.setDate(to.getDate()+1);return{from,to}}const from=new Date(),to=new Date(from);to.setDate(to.getDate()+90);return{from,to}}
function calendarCandidate(event){const start=event.start?.dateTime||event.start?.date||"",end=event.end?.dateTime||event.end?.date||"";return{id:event.id,summary:event.summary||"Sin título",location:event.location||"",start,end,when:calendarWhen(start,event.start?.dateTime?false:true),allDay:!event.start?.dateTime}}
function calendarWhen(value,allDay){if(!value)return"Fecha no disponible";if(allDay)return new Date(`${value}T12:00:00`).toLocaleDateString("es-ES",{dateStyle:"medium"});return new Date(value).toLocaleString("es-ES",{dateStyle:"medium",timeStyle:"short"})}
function calendarPatch(event,changes){const body={};if(changes.title)body.summary=changes.title;if(changes.location)body.location=changes.location;if(changes.notes)body.description=changes.notes;if(changes.date||changes.time){if(event.allDay){if(!changes.date)return body;const end=new Date(`${changes.date}T00:00:00`);end.setDate(end.getDate()+1);body.start={date:changes.date};body.end={date:end.toISOString().slice(0,10)};return body}const currentDate=event.start.slice(0,10),currentTime=event.start.slice(11,16),date=changes.date||currentDate,time=changes.time||currentTime;body.start={dateTime:calendarDateTime(date,time),timeZone:"Europe/Madrid"};body.end={dateTime:calendarEndWithDuration(date,time,event.start,event.end),timeZone:"Europe/Madrid"}}return body}
function calendarEndWithDuration(date,time,originalStart,originalEnd){const start=new Date(calendarDateTime(date,time)),from=new Date(originalStart),to=new Date(originalEnd),duration=Math.max(0,to-from)||60*60*1000,end=new Date(start.getTime()+duration);return`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,"0")}-${String(end.getDate()).padStart(2,"0")}T${String(end.getHours()).padStart(2,"0")}:${String(end.getMinutes()).padStart(2,"0")}:00`}
