const GOOGLE_CLIENT_ID="172772694205-7sigc4s8lkhebs4dtjjvj6huptj10tt0.apps.googleusercontent.com";
const GOOGLE_CONTACTS_SCOPE="https://www.googleapis.com/auth/contacts.readonly";
const GOOGLE_CALENDAR_SCOPE="https://www.googleapis.com/auth/calendar.events";

export function createGoogleIntegration({notify,refresh,setStatus,saveNotes,getNotes}){let contactsToken="",contactsExpiresAt=0,calendarToken="",calendarExpiresAt=0,contactsExpired=false,calendarExpired=false,identityPromise=null;const contactResults=new Map(),calendarInFlight=new Set();
 function contactsValid(){if(contactsToken&&Date.now()<contactsExpiresAt)return true;if(contactsToken)contactsExpired=true;contactsToken="";contactsExpiresAt=0;return false}
 function calendarValid(){if(calendarToken&&Date.now()<calendarExpiresAt)return true;if(calendarToken)calendarExpired=true;calendarToken="";calendarExpiresAt=0;return false}
 function updateStatus(){if(!GOOGLE_CLIENT_ID){setStatus({contacts:"Contactos sin configurar",calendar:"Calendario sin configurar"});return}setStatus({contacts:contactsValid()?"Contactos conectados en esta sesión":contactsExpired?"Contactos: autorización caducada":"Contactos no conectados",calendar:calendarValid()?"Calendario conectado en esta sesión":calendarExpired?"Calendario: autorización caducada":"Calendario no conectado"})}
 function loadIdentity(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(identityPromise)return identityPromise;identityPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://accounts.google.com/gsi/client";script.async=true;script.defer=true;script.onload=()=>window.google?.accounts?.oauth2?resolve():reject(new Error("Google Identity no se pudo iniciar"));script.onerror=()=>reject(new Error("No se pudo cargar Google Identity"));document.head.append(script)});return identityPromise}
 async function connectContacts(){if(!GOOGLE_CLIENT_ID){notify("Google Contacts aún no está configurado");return false}try{await loadIdentity();await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:GOOGLE_CONTACTS_SCOPE,callback:response=>{if(response.error){reject(new Error(response.error));return}contactsToken=response.access_token;contactsExpiresAt=Date.now()+Math.max(0,Number(response.expires_in||0)-30)*1000;contactsExpired=false;resolve()},error_callback:error=>reject(new Error(error.type||"No se pudo autorizar Contactos"))});client.requestAccessToken({prompt:"select_account"})});updateStatus();notify("Contactos conectados para esta sesión");return true}catch(e){updateStatus();notify("No se pudo conectar Contactos");return false}}
 async function connectCalendar(){if(!GOOGLE_CLIENT_ID){notify("Google Calendar aún no está configurado");return false}try{await loadIdentity();await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:GOOGLE_CALENDAR_SCOPE,callback:response=>{if(response.error){reject(new Error(response.error));return}calendarToken=response.access_token;calendarExpiresAt=Date.now()+Math.max(0,Number(response.expires_in||0)-30)*1000;calendarExpired=false;resolve()},error_callback:error=>reject(new Error(error.type||"No se pudo autorizar Calendario"))});client.requestAccessToken({prompt:"select_account"})});updateStatus();notify("Calendario conectado para esta sesión");return true}catch(e){updateStatus();notify("No se pudo conectar Calendario");return false}}
 function disconnectContacts(){contactsToken="";contactsExpiresAt=0;contactsExpired=false;contactResults.clear();updateStatus();refresh();notify("Contactos desconectados de esta sesión")}
 function disconnectCalendar(){calendarToken="";calendarExpiresAt=0;calendarExpired=false;updateStatus();notify("Calendario desconectado de esta sesión")}
 async function searchContact(note){const query=note.contactQuery;if(!query){notify("No hay un nombre de contacto para buscar");return}if(!contactsValid()){contactResults.set(note.id,{contacts:[],error:"Conecta Contactos con la cuenta donde está tu agenda y vuelve a buscar."});updateStatus();refresh();return}const url=value=>`https://people.googleapis.com/v1/people:searchContacts?${new URLSearchParams({query:value,readMask:"names,phoneNumbers",pageSize:"10",sources:"READ_SOURCE_TYPE_CONTACT"})}`,request=value=>fetch(url(value),{headers:{Authorization:`Bearer ${contactsToken}`}});try{const warmup=await request("");if(!warmup.ok)throw new Error(String(warmup.status));const response=await request(query);if(!response.ok)throw new Error(String(response.status));const data=await response.json(),contacts=(data.results||[]).map(result=>result.person||{}).map(person=>({name:person.names?.[0]?.displayName||query,phones:(person.phoneNumbers||[]).map(contactPhoneValue).filter(Boolean)}));contactResults.set(note.id,{contacts});refresh()}catch(e){if(e.message==="401"||e.message==="403"){contactsToken="";contactsExpiresAt=0;contactsExpired=true;updateStatus()}contactResults.set(note.id,{contacts:[],error:"No se pudo consultar los contactos. Conecta Contactos de nuevo con la cuenta correcta."});refresh()}}
 async function createCalendarEvent(note){if(note.calendarStatus==="synced"&&note.calendarEventId){notify("Esta entrada ya está añadida al calendario");return}if(!note.scheduledDate){notify("Falta la fecha para crear el evento");return}if(!note.scheduledTime){notify("Falta la hora para crear el evento");return}if(calendarInFlight.has(note.id))return;const start=calendarDateTime(note.scheduledDate,note.scheduledTime),display=new Date(start).toLocaleString("es-ES",{dateStyle:"medium",timeStyle:"short"});if(!confirm(`¿Añadir al calendario?\n${calendarEventTitle(note.text)}\n${display}`))return;calendarInFlight.add(note.id);let eventCreated=false;try{if(!calendarValid()&&!(await connectCalendar()))return;const eventId=note.calendarEventId||calendarEventKey(note),endpoint="https://www.googleapis.com/calendar/v3/calendars/primary/events",options={method:"POST",headers:{Authorization:`Bearer ${calendarToken}`,"Content-Type":"application/json"},body:JSON.stringify({id:eventId,summary:calendarEventTitle(note.text),start:{dateTime:start,timeZone:"Europe/Madrid"},end:{dateTime:calendarEndDateTime(note.scheduledDate,note.scheduledTime),timeZone:"Europe/Madrid"}})};let response=await fetch(endpoint,options),event;if(response.status===409)response=await fetch(`${endpoint}/${encodeURIComponent(eventId)}`,{headers:{Authorization:`Bearer ${calendarToken}`}});if(!response.ok)throw new Error(String(response.status));event=await response.json();eventCreated=true;if(!saveNotes(getNotes().map(item=>item.id===note.id?{...item,calendarStatus:"synced",calendarEventId:event.id||eventId,calendarUrl:event.htmlLink||""}:item))){notify("El evento se creó, pero no se pudo marcar localmente. Reintenta sin crear duplicados.");return}notify("Evento añadido al calendario")}catch(e){if(!eventCreated){saveNotes(getNotes().map(item=>item.id===note.id?{...item,calendarStatus:"error"}:item));notify("No se pudo añadir el evento al calendario")}}finally{calendarInFlight.delete(note.id)}}
 return{updateStatus,connectContacts,connectCalendar,disconnectContacts,disconnectCalendar,searchContact,createCalendarEvent,getContactResult:id=>contactResults.get(id),clearContactResult:id=>contactResults.delete(id),contactTel};
}

function contactPhoneValue(phone){return(phone?.value||"").trim()}
function contactTel(phone){return contactPhoneValue({value:phone}).replace(/[^\d+]/g,"")}
function calendarEventTitle(text){return(text||"").replace(/^\s*(?:apunta(?:\s+en\s+el\s+calendario)?|añade(?:\s+al\s+calendario)?|agrega(?:\s+al\s+calendario)?)\b\s*/i,"").replace(/\bmañana\b/gi,"").replace(/\b\d{2}\/\d{2}\/\d{4}\b/g,"").replace(/\ba\s+las\s+(?:[01]?\d|2[0-3])(?::[0-5]\d)?\b/gi,"").replace(/\b(?:[01]?\d|2[0-3]):[0-5]\d\b/g,"").replace(/\s{2,}/g," ").replace(/^[\s,.:;-]+|[\s,.:;-]+$/g,"").trim()||"Evento de Angeli Secretaria"}
function calendarDateTime(date,time){return`${date}T${time}:00`}
function calendarEndDateTime(date,time){const end=new Date(calendarDateTime(date,time));end.setHours(end.getHours()+1);return`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,"0")}-${String(end.getDate()).padStart(2,"0")}T${String(end.getHours()).padStart(2,"0")}:${String(end.getMinutes()).padStart(2,"0")}:00`}
function calendarEventKey(note){return`angeli${note.id.replace(/-/g,"")}`}
