const MONTHS={enero:0,febrero:1,marzo:2,abril:3,mayo:4,junio:5,julio:6,agosto:7,septiembre:8,octubre:9,noviembre:10,diciembre:11};
const WEEKDAYS={domingo:0,lunes:1,martes:2,miércoles:3,jueves:4,viernes:5,sábado:6};
const HOURS={una:1,uno:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12};

export function temporalData(text,now=new Date()){const value=(text||"").toLowerCase(),data={},date=extractDate(value,now),time=extractTime(value);if(date)data.scheduledDate=toDateKey(date);if(time)data.scheduledTime=`${String(time.hour).padStart(2,"0")}:${String(time.minute).padStart(2,"0")}`;return data}
export function calendarQueryRange(text,now=new Date()){const value=(text||"").toLowerCase();if(/\b(?:la\s+)?(?:semana\s+que\s+viene|próxima\s+semana)\b/.test(value)){const start=startOfWeek(now);start.setDate(start.getDate()+7);const end=new Date(start);end.setDate(end.getDate()+7);return{rangeStart:toDateKey(start),rangeEnd:toDateKey(end)}}if(/\besta\s+semana\b/.test(value)){const start=startOfWeek(now),end=new Date(start);end.setDate(end.getDate()+7);return{rangeStart:toDateKey(start),rangeEnd:toDateKey(end)}}const date=extractDate(value,now);if(!date)return null;const start=toDateKey(date),end=new Date(date);end.setDate(end.getDate()+1);return{rangeStart:start,rangeEnd:toDateKey(end)}}

function extractDate(value,now){if(/\bmañana\b/.test(value)){const date=new Date(now);date.setDate(date.getDate()+1);return date}const numeric=value.match(/\b(\d{1,2})\/(\d{1,2})\/(\d{4})\b/);if(numeric)return validDate(Number(numeric[3]),Number(numeric[2])-1,Number(numeric[1]));const named=value.match(/\b(\d{1,2})\s+de\s+(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(?:\s+de\s+(\d{4}))?\b/);if(named){let year=named[3]?Number(named[3]):now.getFullYear(),date=validDate(year,MONTHS[named[2]],Number(named[1]));if(date&&!named[3]&&date<startOfToday(now))date=validDate(year+1,MONTHS[named[2]],Number(named[1]));return date}const weekday=value.match(/\b(domingo|lunes|martes|miércoles|jueves|viernes|sábado)\b/);if(weekday){const date=new Date(now),target=WEEKDAYS[weekday[1]],delta=(target-date.getDay()+7)%7||7;date.setDate(date.getDate()+delta);return date}return null}
function extractTime(value){const numeric=value.match(/(?:\ba\s+las\s+)(2[0-3]|[01]?\d)(?::([0-5]\d))?(?:\s+de\s+la\s+(mañana|tarde|noche))?|\b(2[0-3]|[01]?\d):([0-5]\d)\b/);if(numeric){let hour=Number(numeric[1]||numeric[4]),minute=Number(numeric[2]||numeric[5]||0);return normalizeHour(hour,minute,numeric[3])}const words=value.match(/\ba\s+las\s+(una|uno|dos|tres|cuatro|cinco|seis|siete|ocho|nueve|diez|once|doce)(?:\s+(y\s+media|y\s+cuarto|menos\s+cuarto))?(?:\s+de\s+la\s+(mañana|tarde|noche))?\b/);if(!words)return null;let hour=HOURS[words[1]],minute=0;if(words[2]==="y media")minute=30;if(words[2]==="y cuarto")minute=15;if(words[2]==="menos cuarto"){hour=hour===1?12:hour-1;minute=45}return normalizeHour(hour,minute,words[3])}
function normalizeHour(hour,minute,part){if(part==="tarde"&&hour<12)hour+=12;if(part==="noche"){if(hour===12)hour=0;else if(hour<12)hour+=12}return{hour,minute}}
function validDate(year,month,day){const date=new Date(year,month,day,12);return date.getFullYear()===year&&date.getMonth()===month&&date.getDate()===day?date:null}
function startOfToday(now){return new Date(now.getFullYear(),now.getMonth(),now.getDate())}
function startOfWeek(now){const date=startOfToday(now),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);return date}
function toDateKey(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}

export function cleanTemporalText(text){return(text||"").replace(/^\s*(?:apunta(?:\s+en\s+el\s+calendario)?|añade(?:\s+al\s+calendario)?|agrega(?:\s+al\s+calendario)?)\b\s*/i,"").replace(/\b(?:para\s+(?:el\s+)?)?(?:mañana|domingo|lunes|martes|miércoles|jueves|viernes|sábado|\d{1,2}\/\d{1,2}\/\d{4}|\d{1,2}\s+de\s+(?:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)(?:\s+de\s+\d{4})?)\b/gi,"").replace(/\ba\s+las\s+(?:(?:2[0-3]|[01]?\d)(?::[0-5]\d)?|una|uno|dos|tres|cuatro|cinco|seis|siete|ocho|nueve|diez|once|doce)(?:\s+(?:y\s+media|y\s+cuarto|menos\s+cuarto))?(?:\s+de\s+la\s+(?:mañana|tarde|noche))?\b/gi,"").replace(/\b(?:2[0-3]|[01]?\d):[0-5]\d\b/g,"").replace(/\s{2,}/g," ").replace(/\s+([,.:;-])/g,"$1").replace(/^[\s,.:;-]+|[\s,.:;-]+$/g,"").trim()||"Evento de Angeli Secretaria"}
