import{typeLabel}from"./classifier.js?v=0.16.2";

export function createUI({getMedia}){const $=id=>document.getElementById(id);let toastTimer;
 function notify(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
 function setGoogleStatus({contacts,calendar,ai}){$("contactsStatus").textContent=contacts;$("calendarStatus").textContent=calendar;$("aiStatus").textContent=ai}
 function closeLayers(){$("actionModal").classList.remove("show");$("settingsMenu").classList.remove("show");$("scrim").classList.remove("show")}
 function openMenu(){$("scrim").classList.add("show");$("settingsMenu").classList.add("show")}
 function openModal({title,lead,body,actions=[]}){$("modalTitle").textContent=title;$("modalLead").textContent=lead;const box=$("modalBody");box.innerHTML="";if(typeof body==="string")box.innerHTML=body;else if(body)box.append(body);const area=$("modalActions");area.innerHTML="";actions.forEach(action=>{const button=document.createElement("button");button.textContent=action.label;button.className=action.kind||"secondary";if(action.dataset)Object.entries(action.dataset).forEach(([key,value])=>button.dataset[key]=value);if(action.onClick)button.onclick=action.onClick;area.append(button)});$("scrim").classList.add("show");$("actionModal").classList.add("show")}
 function entryBody(note){const proposal=note.proposal,description=proposal?.description||"Entrada guardada";return`<div class="proposal-box"><strong>${esc(typeLabel(note.type))}</strong>${esc(description)}${note.location?`<br>📍 ${esc(note.location)}`:""}</div>`}
 function showEntryAction(note){const intent=note.proposal?.intent||"note",base={title:"Entrada preparada",lead:"Angeli ha entendido esto. Confirma solo si quieres realizar la acción.",body:entryBody(note)};if(intent==="calendar.create")return openModal({...base,title:"¿Lo añado al calendario?",actions:[{label:"Seguir editando",kind:"secondary",onClick:()=>{closeLayers();$("text").value=note.text;$("text").focus()}},{label:"📅 Añadir",kind:"confirm",dataset:{a:"calendar",id:note.id}}]});if(intent==="contact.call")return openModal({...base,title:"Llamar",actions:[{label:"Ahora no",kind:"secondary",onClick:closeLayers},{label:note.phone?"📞 Abrir marcador":"👥 Buscar contacto",kind:"confirm",dataset:{a:note.phone?"call":"search-contact",id:note.id,phone:note.phone||""}}]});if(["calendar.query","calendar.update","calendar.delete"].includes(intent))return openModal({...base,title:intent==="calendar.query"?"Consultar calendario":intent==="calendar.update"?"Modificar evento":"Cancelar evento",actions:[{label:"Ahora no",kind:"secondary",onClick:closeLayers},{label:intent==="calendar.query"?"📅 Consultar":"Buscar coincidencias",kind:"confirm",dataset:{a:"search-calendar",id:note.id}}]});return openModal({...base,title:"Guardado",lead:"La entrada se ha guardado en tu conversación.",actions:[{label:"Cerrar",kind:"confirm",onClick:closeLayers}]})}
 function calendarActions(note,google){const intent=note.proposal?.intent;if(note.calendarStatus==="synced")return`<div class="done-message">✓ Añadido al calendario${note.calendarUrl?` · <a href="${esc(note.calendarUrl)}" target="_blank" rel="noopener">Abrir</a>`:""}</div>`;if(note.calendarStatus==="cancelled")return'<div class="done-message">✓ Evento cancelado</div>';if(intent==="calendar.create")return`<div class="inline-actions"><button class="small-btn primary" data-a="show-action" data-id="${note.id}">📅 Ver acción</button></div>`;const result=google.getCalendarResult(note.id);if(!result)return`<div class="inline-actions"><button class="small-btn primary" data-a="show-action" data-id="${note.id}">Ver acción</button></div>`;if(result.error)return`<div class="card-details meta">${esc(result.error)}</div>`;if(!result.events.length)return'<div class="card-details meta">No he encontrado coincidencias.</div>';return`<div class="card-details">${result.events.map(event=>`<div class="choice"><div><b>${esc(event.summary)}</b><span>${esc(event.when)}</span></div>${intent==="calendar.delete"?`<button class="small-btn danger" data-a="calendar-delete" data-id="${note.id}" data-event-id="${esc(event.id)}">Cancelar</button>`:intent==="calendar.update"?`<button class="small-btn primary" data-a="calendar-update" data-id="${note.id}" data-event-id="${esc(event.id)}">Modificar</button>`:""}</div>`).join("")}</div>`}
 function contactActions(note,google){if(note.phone)return`<div class="inline-actions"><a class="small-btn primary" href="tel:${esc(note.phone)}">📞 Llamar</a></div>`;const result=google.getContactResult(note.id);if(!result)return`<div class="inline-actions"><button class="small-btn primary" data-a="show-action" data-id="${note.id}">📞 Ver acción</button></div>`;if(result.error)return`<div class="card-details meta">${esc(result.error)}</div>`;const contacts=result.contacts.flatMap(contact=>contact.phones.map(phone=>`<a class="small-btn primary" href="tel:${esc(google.contactTel(phone))}">📞 ${esc(contact.name)}</a>`));return contacts.length?`<div class="inline-actions">${contacts.join("")}</div>`:`<div class="card-details meta">No he encontrado a ${esc(note.contactQuery||"ese contacto")} en contactos.</div>`}
 async function hydrateImages(){for(const image of document.querySelectorAll("img[data-image-id]")){try{const media=await getMedia("images",image.dataset.imageId);if(media){const url=URL.createObjectURL(media.blob);image.src=url;image.dataset.objectUrl=url}}catch(e){}}}
 function render({notes,selectedFilter,selectedType,google}){document.querySelectorAll("img[data-object-url]").forEach(image=>URL.revokeObjectURL(image.dataset.objectUrl));const query=$("search").value.toLowerCase().trim(),shown=notes.filter(note=>(selectedFilter==="all"||note.status===selectedFilter)&&(selectedType==="all"||note.type===selectedType)&&(!query||(note.text+" "+(note.files||[]).map(file=>file.name||file).join(" ")).toLowerCase().includes(query)));$("list").innerHTML=shown.length?`<div class="day">Entradas recientes</div>${shown.map(note=>`<article data-entry-id="${note.id}"><div class="message me"><div class="bubble">${esc(note.text||"Entrada con adjunto")}</div></div><div class="message angeli"><div class="avatar">A</div><div class="bubble"><span class="badge">${esc(typeLabel(note.type))}</span><br>${esc(note.proposal?.description||"Guardado en Angeli")}${note.location?`<div class="meta">📍 ${esc(note.location)}</div>`:""}</div></div>${note.images?.length?`<div class="media">${note.images.map(id=>`<img class="thumb" data-image-id="${id}" alt="Imagen adjunta">`).join("")}</div>`:""}${note.files?.length?`<div class="file-line">${note.files.map(file=>`<button class="small-btn" data-a="open-file" data-id="${note.id}" data-media-id="${file.id}">📎 ${esc(file.name)}</button>`).join(" ")}</div>`:""}${note.type==="calendar"?calendarActions(note,google):note.type==="contact"?contactActions(note,google):""}<div class="inline-actions"><button class="small-btn" data-a="toggle" data-id="${note.id}">${note.status==="done"?"Reabrir":"✓ Hecho"}</button><button class="small-btn danger" data-a="delete" data-id="${note.id}">Borrar</button></div></article>`).join(""):'<div class="empty">No hay entradas que mostrar.</div>';hydrateImages()}
 function showImagePreview(files){$("preview").innerHTML=files.map(file=>`<img class="thumb" src="${URL.createObjectURL(file)}" alt="Imagen preparada">`).join("")}
 return{$,notify,setGoogleStatus,render,showImagePreview,showEntryAction,openModal,openMenu,closeLayers};
}
function esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
