import{typeLabel}from"./classifier.js?v=0.14";

export function createUI({getMedia}){const $=id=>document.getElementById(id);let toastTimer;
 function notify(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
 function setGoogleStatus({contacts,calendar}){$("contactsStatus").textContent=contacts;$("calendarStatus").textContent=calendar}
 function calendarMarkup(note){if(note.calendarStatus==="synced"&&note.calendarEventId)return`<div class="actions"><span class="calendar-synced">✓ Añadido al calendario</span>${note.calendarUrl?`<a class="small-btn" href="${esc(note.calendarUrl)}" target="_blank" rel="noopener">Abrir evento</a>`:""}</div>`;const retry=note.calendarStatus==="error"?"Reintentar calendario":"📅 Añadir al calendario";return`${note.calendarStatus==="error"?'<div class="meta">No se pudo sincronizar con Google Calendar.</div>':""}<div class="actions"><button class="small-btn" data-a="calendar" data-id="${note.id}">${retry}</button></div>`}
 function contactMarkup(note,google){if(note.phone)return`<div class="actions"><a class="small-btn" href="tel:${note.phone}">📞 Llamar</a></div>`;if(!note.contactQuery)return`<div class="actions"><button class="small-btn" data-a="contact" data-id="${note.id}">📞 Llamar</button></div>`;const result=google.getContactResult(note.id);if(!result)return`<div class="actions"><button class="small-btn" data-a="search-contact" data-id="${note.id}">📞 Buscar en contactos</button></div>`;if(result.error)return`<div class="meta">${esc(result.error)}</div>`;if(!result.contacts.length)return`<div class="meta">No he encontrado a ${esc(note.contactQuery)} en contactos</div>`;const withPhone=result.contacts.filter(contact=>contact.phones.length);if(!withPhone.length)return`<div class="meta">He encontrado a ${esc(note.contactQuery)}, pero no tiene teléfono disponible</div>`;return`<div class="contact-options">${withPhone.flatMap(contact=>contact.phones.map(phone=>`<div class="contact-option"><span>${esc(contact.name)} · ${esc(phone)}</span><a class="small-btn" href="tel:${google.contactTel(phone)}">📞 Llamar</a></div>`)).join("")}</div>`}
 async function hydrateImages(){for(const image of document.querySelectorAll("img[data-image-id]")){try{const media=await getMedia("images",image.dataset.imageId);if(media){const url=URL.createObjectURL(media.blob);image.src=url;image.dataset.objectUrl=url}}catch(e){}}}
 function render({notes,selectedFilter,selectedType,google}){document.querySelectorAll("img[data-object-url]").forEach(image=>URL.revokeObjectURL(image.dataset.objectUrl));const q=$("search").value.toLowerCase().trim(),arr=notes.filter(n=>(selectedFilter==="all"||n.status===selectedFilter)&&(selectedType==="all"||n.type===selectedType)&&(!q||(n.text+" "+(n.files||[]).map(f=>f.name).join(" ")).toLowerCase().includes(q)));$("list").innerHTML=arr.length?arr.map(n=>`<article class="card ${n.status==="done"?"done":""}"><div class="meta"><span class="badge">${typeLabel(n.type)}</span> · ${new Date(n.date).toLocaleDateString("es-ES")}</div><div class="note-text">${esc(n.text||"Entrada con archivo o imagen")}</div>${n.type==="task"?'<div class="meta">Tarea pendiente</div>':n.type==="reminder"?'<div class="meta">Recordatorio pendiente de programar</div>':""}${n.images?.length?`<div class="card-media">${n.images.map(id=>`<img class="thumb" data-image-id="${id}" alt="">`).join("")}</div>`:""}${n.files?.length?`<div class="file-line">📎 ${n.files.map(f=>f.id?`<button class="small-btn" data-a="open-file" data-id="${n.id}" data-media-id="${f.id}">${esc(f.name)}</button>`:esc(f.name||f)).join(" · ")}</div>`:""}${n.type==="calendar"?calendarMarkup(n):""}${n.type==="contact"?contactMarkup(n,google):""}<div class="actions"><button class="small-btn" data-a="toggle" data-id="${n.id}">${n.status==="done"?"Reabrir":"✓ Hecho"}</button><button class="small-btn" data-a="delete" data-id="${n.id}">Borrar</button></div></article>`).join(""):'<div class="empty">No hay entradas.</div>';hydrateImages()}
 function showImagePreview(files){$("preview").innerHTML=files.map(file=>`<img class="thumb" src="${URL.createObjectURL(file)}" alt="">`).join("")}
 return{$,notify,setGoogleStatus,render,showImagePreview};
}

function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
