const V="0.22.7",CACHE="angeli-secretaria-v"+V;
importScripts("https://www.gstatic.com/firebasejs/11.10.0/firebase-app-compat.js","https://www.gstatic.com/firebasejs/11.10.0/firebase-messaging-compat.js");
firebase.initializeApp({apiKey:"AIzaSyAFM5NjcxX9lC5MpfII4B3Kx7lV9SsUAsc",authDomain:"angeli-secretaria.firebaseapp.com",projectId:"angeli-secretaria",storageBucket:"angeli-secretaria.firebasestorage.app",messagingSenderId:"172772694205",appId:"1:172772694205:web:6ce976de4a3658c12f3fd4"});
firebase.messaging().onBackgroundMessage(payload=>{const data=payload.data||{};return self.registration.showNotification(data.title||"Angeli",{body:data.body||"Tienes un recordatorio.",icon:"icon-192.png",badge:"icon-192.png",tag:data.entryId||"angeli-test",data:{url:data.url||"./"}})});
const ASSETS=["./?v="+V,"./index.html?v="+V,"./styles.css?v="+V,"./styles-flow.css?v="+V,"./manifest.json?v="+V,"./js/app.js?v="+V,"./js/agenda.js?v="+V,"./js/dietario.js?v="+V,"./js/ui.js?v="+V,"./js/storage.js?v="+V,"./js/classifier.js?v="+V,"./js/temporal.js?v="+V,"./js/google.js?v="+V,"./js/sheets.js?v="+V,"./js/ai.js?v="+V,"./js/intents.js?v="+V,"./js/conversation.js?v="+V,"./js/pending.js?v="+V,"./js/schedule.js?v="+V,"./js/firebase.js?v="+V,"./js/media.js?v="+V,"./js/media-library.js?v="+V,"./js/media-context.js?v="+V,"./js/shortcuts.js?v="+V,"./js/whatsapp.js?v="+V,"./js/notification-settings.js?v="+V,"./js/shopping.js?v="+V,"./icon-192.png?v="+V,"./icon-512.png?v="+V,"./assets/angeli-welcome.gif?v="+V];
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url),fresh=e.request.mode==="navigate"||/\/(index\.html|manifest\.json|sw\.js)$/.test(u.pathname)||/\.(js|css)$/.test(u.pathname);if(fresh){e.respondWith(fetch(e.request,{cache:"no-store"}).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(e.request,c));return r}).catch(()=>caches.match(e.request)));}else e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)))});
self.addEventListener("notificationclick",event=>{event.notification.close();const target=new URL(event.notification.data?.url||"./",self.registration.scope).href;event.waitUntil(clients.matchAll({type:"window",includeUncontrolled:true}).then(windows=>{const visible=windows[0];if(visible){visible.navigate(target);return visible.focus()}return clients.openWindow(target)}))});
